# Generated by Django 5.1 on 2024-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_rename_day_lucky_day_lucky_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lucky_day',
            name='lucky_day',
            field=models.DateField(),
        ),
    ]
