# Generated by Django 5.1 on 2024-08-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_lucky_day_lucky_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lucky_day',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lucky_day',
            name='office_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.office_employee'),
        ),
    ]
