# Generated by Django 5.1 on 2024-08-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_lucky_day_added_date_lucky_day_office_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('party_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('event_day', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField()),
                ('office_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.office_employee')),
            ],
        ),
    ]
