# Generated by Django 5.1 on 2024-08-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_count',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.event_count'),
        ),
    ]
