# Generated by Django 5.1 on 2024-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_remove_event_event_count_delete_event_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='persons',
            field=models.IntegerField(null=True),
        ),
    ]
