# Generated by Django 5.1 on 2024-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_event_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='persons',
            new_name='persons_day',
        ),
        migrations.AddField(
            model_name='event',
            name='persons_night',
            field=models.IntegerField(null=True),
        ),
    ]
